# Generated by Django 4.2.7 on 2026-01-23 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted/Archived'), ('publish', 'Published'), ('unpublish', 'Unpublished'), ('duplicate', 'Duplicated'), ('ai_generate', 'AI Generated')], db_index=True, max_length=20)),
                ('object_type', models.CharField(help_text='Course, Chapter, Topic, etc.', max_length=50)),
                ('object_id', models.IntegerField(help_text='ID of affected object')),
                ('changes', models.JSONField(default=dict, help_text='{ "field": {"old": value, "new": value} }')),
                ('reason', models.TextField(blank=True, help_text='Why this change was made')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Chapter overview')),
                ('order_index', models.IntegerField(db_index=True, default=0)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_chapters',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('paused', 'Paused')], db_index=True, default='active', max_length=20)),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Percentage of topics completed')),
                ('completed_topics_count', models.IntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_enrollments',
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief topic summary')),
                ('content', models.TextField(help_text='Markdown content with code blocks, images via ![](asset_id)')),
                ('estimated_minutes', models.IntegerField(default=15, help_text='Estimated time for student to complete')),
                ('order_index', models.IntegerField(db_index=True, default=0)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('key_concepts', models.JSONField(default=list, help_text='Array of main concepts covered')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='True if created/substantially modified by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course_topics',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('snapshot', models.JSONField(help_text='Complete course structure snapshot')),
                ('change_summary', models.TextField(blank=True, help_text='What changed in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Percentage scored (0.0-1.0)')),
                ('passed', models.BooleanField(db_index=True)),
                ('answers', models.JSONField(default=dict, help_text='{ question_id: choice_id }')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('time_spent_minutes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'quiz_choices',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='multiple_choice', max_length=20)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Shown to student after answering')),
                ('order_index', models.IntegerField(default=0)),
                ('difficulty_multiplier', models.FloatField(default=1.0, help_text='Weight for scoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('java', 'Java'), ('cpp', 'C++'), ('bash', 'Bash'), ('other', 'Other')], db_index=True, max_length=50)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Explanation of what this code does')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_executable', models.BooleanField(default=False, help_text='Can this code be executed by students?')),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_code',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'student_notes',
            },
        ),
        migrations.CreateModel(
            name='TopicAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('code', 'Source Code'), ('diagram', 'Diagram'), ('pdf', 'PDF Document'), ('video', 'Video Link')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='topics/assets/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for images (SEO + accessibility)', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topic_assets',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TopicBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topic_bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topic_progress',
            },
        ),
        migrations.CreateModel(
            name='TopicQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Practice Quiz', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.FloatField(default=0.7, help_text='Percentage required to pass (0.0-1.0)')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('show_feedback_immediately', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'topic_quizzes',
            },
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_accessed_subtopic',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='personalchapter',
            name='personal_course',
        ),
        migrations.RemoveField(
            model_name='personalcourse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personaltopic',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.AlterUniqueTogether(
            name='subtopicprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subtopicprogress',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='subtopicprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='chapter',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('can_publish_course', 'Can publish courses to production'), ('can_view_audit_log', 'Can view course audit logs'), ('can_use_ai_tools', 'Can use AI-assisted content generation')]},
        ),
        migrations.RemoveField(
            model_name='course',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(db_index=True, default='other', help_text='Course category for filtering', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_hours',
            field=models.IntegerField(default=10, help_text='Estimated time to complete (calculated from topics)'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (< 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for search engines (< 60 chars)', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Publishing'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Course overview for listing page'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.JSONField(default=list, help_text='Array of topic tags for search'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Course card image (optimal: 400x300px)', null=True, upload_to='courses/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_slug_360be0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'published_at'], name='courses_status_7d1705_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_categor_33f89e_idx'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='PersonalChapter',
        ),
        migrations.DeleteModel(
            name='PersonalCourse',
        ),
        migrations.DeleteModel(
            name='PersonalTopic',
        ),
    ]
