# Generated by Django 4.2.7 on 2026-01-23 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auditlog_coursechapter_courseenrollment_coursetopic_and_more'),
        ('notes', '0002_alter_note_course_subtopic_alter_note_course_topic'),
        ('roadmaps', '0002_alter_roadmaptask_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.DeleteModel(
            name='SubtopicProgress',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='topicquiz',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.coursetopic'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='courses.courseenrollment'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.coursetopic'),
        ),
        migrations.AddField(
            model_name='topicbookmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicbookmark',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='courses.coursetopic'),
        ),
        migrations.AddField(
            model_name='topicasset',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='courses.coursetopic'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.coursetopic'),
        ),
        migrations.AddField(
            model_name='sourcecode',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='courses.coursetopic'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.topicquiz'),
        ),
        migrations.AddField(
            model_name='quizchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.topicquiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.coursechapter'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Topics that should be completed first', to='courses.coursetopic'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='courses.course'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='topicquiz',
            unique_together={('topic',)},
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['enrollment', 'status'], name='topic_progr_enrollm_69d5be_idx'),
        ),
        migrations.AddIndex(
            model_name='topicprogress',
            index=models.Index(fields=['topic'], name='topic_progr_topic_i_b562ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together={('enrollment', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='topicbookmark',
            unique_together={('student', 'topic')},
        ),
        migrations.AddIndex(
            model_name='topicasset',
            index=models.Index(fields=['type'], name='topic_asset_type_cd17ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentnote',
            unique_together={('student', 'topic')},
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='quiz_attemp_student_1efa68_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['passed'], name='quiz_attemp_passed_e7138e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseversion',
            unique_together={('course', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='coursetopic',
            index=models.Index(fields=['chapter', 'order_index'], name='course_topi_chapter_3ec4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetopic',
            index=models.Index(fields=['is_archived'], name='course_topi_is_arch_43f2b8_idx'),
        ),
        migrations.AddIndex(
            model_name='coursetopic',
            index=models.Index(fields=['is_ai_generated'], name='course_topi_is_ai_g_0ae7f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetopic',
            unique_together={('chapter', 'slug')},
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'status'], name='course_enro_student_8023bd_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'status'], name='course_enro_course__37db5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='coursechapter',
            index=models.Index(fields=['course', 'order_index'], name='course_chap_course__513fab_idx'),
        ),
        migrations.AddIndex(
            model_name='coursechapter',
            index=models.Index(fields=['is_archived'], name='course_chap_is_arch_8875c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursechapter',
            unique_together={('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['course', 'created_at'], name='audit_logs_course__56cf25_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
    ]
