# Generated by Django 4.2.7 on 2026-01-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auditlog_coursechapter_courseenrollment_coursetopic_and_more'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='course_subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopic_notes', to='courses.coursetopic'),
        ),
        migrations.AlterField(
            model_name='note',
            name='course_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursetopic'),
        ),
    ]
