# Generated by Django 4.2.7 on 2025-12-23 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('summarize_short', 'Short Summary'), ('summarize_medium', 'Medium Summary'), ('summarize_detailed', 'Detailed Summary'), ('expand', 'Content Expansion'), ('rewrite', 'Rewrite for Clarity'), ('breakdown', 'Topic Breakdown'), ('from_transcript', 'From YouTube Transcript'), ('from_text', 'From Raw Text')], max_length=50)),
                ('source_content', models.TextField()),
                ('generated_content', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_generated_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyNoteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('notes_created', models.IntegerField(default=0)),
                ('notes_updated', models.IntegerField(default=0)),
                ('topics_covered', models.JSONField(blank=True, default=list)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='daily_reports/')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_note_reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='NoteShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Read Only'), ('edit', 'Can Edit')], default='view', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'note_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube Video'), ('url', 'Website/URL'), ('pdf', 'PDF Document'), ('article', 'Article'), ('book', 'Book'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('reference_number', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note_sources',
                'ordering': ['reference_number'],
            },
        ),
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_content', models.JSONField(default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content', models.TextField()),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('changes_summary', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('video_id', models.CharField(max_length=100)),
                ('video_title', models.CharField(blank=True, max_length=500)),
                ('transcript', models.TextField()),
                ('timestamps', models.JSONField(blank=True, default=list)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'youtube_transcripts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notehistory',
            name='note',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='note',
            name='content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='note',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=550),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='toc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', '-updated_at'], name='notes_user_id_8a4da1_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'status'], name='notes_user_id_90ed5e_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['session_date'], name='notes_session_907b8c_idx'),
        ),
        migrations.DeleteModel(
            name='NoteHistory',
        ),
        migrations.AddField(
            model_name='youtubetranscript',
            name='notes_generated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.note'),
        ),
        migrations.AddField(
            model_name='youtubetranscript',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_transcripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteversion',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notes.note'),
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notesource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteshare',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='notes.note'),
        ),
        migrations.AddField(
            model_name='noteshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailynotereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aigeneratednote',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to='notes.note'),
        ),
        migrations.AddField(
            model_name='aigeneratednote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.notesource'),
        ),
        migrations.AlterUniqueTogether(
            name='youtubetranscript',
            unique_together={('user', 'video_id')},
        ),
        migrations.AlterUniqueTogether(
            name='noteversion',
            unique_together={('note', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='notesource',
            unique_together={('user', 'reference_number')},
        ),
        migrations.AlterUniqueTogether(
            name='dailynotereport',
            unique_together={('user', 'report_date')},
        ),
    ]
