# Generated by Django 4.2.7 on 2025-12-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='chaptertopic',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('note', 'title'), name='unique_chapter_per_note'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('note', 'order'), name='unique_chapter_order_per_note'),
        ),
        migrations.AddConstraint(
            model_name='chaptertopic',
            constraint=models.UniqueConstraint(fields=('chapter', 'name'), name='unique_topic_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='chaptertopic',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='unique_topic_order_per_chapter'),
        ),
    ]
