# Generated by Django 4.2.7 on 2026-01-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='last_drive_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='upload_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=20),
        ),
    ]
