# Generated by Django 4.2.7 on 2026-01-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_note_drive_file_id_note_last_drive_sync_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('generate_explanation', 'Generate Explanation'), ('improve_explanation', 'Improve Explanation'), ('summarize_explanation', 'Summarize Explanation'), ('generate_code', 'Generate Code')], max_length=50)),
                ('prompt', models.TextField(help_text="User's input/prompt")),
                ('generated_content', models.TextField(help_text='AI generated output')),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('temporary', 'Temporary'), ('saved', 'Saved')], default='temporary', max_length=20)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('drive_folder', models.CharField(blank=True, max_length=100, null=True)),
                ('last_drive_sync_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(help_text='Auto-generated or user-defined title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type'], name='ai_history_user_id_2dc6b9_idx'), models.Index(fields=['user', 'status'], name='ai_history_user_id_c0060b_idx'), models.Index(fields=['created_at'], name='ai_history_created_ee3a97_idx')],
            },
        ),
    ]
